services:

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    networks:
      - airflow-net

  producer:
    build:
      context: ./streaming
      dockerfile: Dockerfile.producer
    image: producer:latest
    container_name: producer
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: stock-data
    networks:
      - airflow-net
    restart: unless-stopped

  consumer:
    build:
      context: ./streaming
      dockerfile: Dockerfile.consumer
    image: consumer:latest
    container_name: consumer
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: stock-data
    networks:
      - airflow-net
    restart: unless-stopped

  spark-stream:
    build:
      context: ./sparkstream
      dockerfile: Dockerfile
    image: spark-stream:latest
    container_name: spark-stream
    depends_on:
      - kafka
    networks:
      - airflow-net

  spark-batch:
    build:
      context: ./sparkjob
      dockerfile: Dockerfile
    image: sparkjob:latest
    container_name: sparkjob
    networks:
      - airflow-net

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - airflow-net

  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - airflow-net

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow-webserver
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - airflow-net

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow-scheduler
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    command: scheduler
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge
