FROM python:3.10-slim

WORKDIR /app

# Copy files from THIS folder (streaming/) into /app
COPY producer.py /app/producer.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "producer.py"]
